# Generated by Django 4.2.4 on 2023-09-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='None', unique=True)),
                ('livebusyness', models.JSONField(blank=True, null=True)),
                ('populartimes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
