# Generated by Django 4.2.4 on 2023-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='livebusyness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='populartimes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
